"use client";

import { useState } from "react";
import { CheckCircle2, XCircle, ArrowRight, BookOpen, ShieldAlert } from "lucide-react";

export interface StyleRule {
  id: string;
  ruleTitle: string;
  category: "Voice & Tone" | "Terminology" | "Code Snippets" | "UX & Errors";
  explanation: string;
  beforeText: string;
  afterText: string;
  why: string;
}

export const STYLE_RULES: StyleRule[] = [
  {
    id: "industrial-edge-terminology",
    ruleTitle: "Enforce Standardized Siemens Industrial Edge Product Names",
    category: "Terminology",
    explanation: "Always use official product terms (IED, IEM, IIH Essentials, Common Configurator, Databus) rather than informal abbreviations.",
    beforeText: "Connect the edge box to the cloud portal and configure the data bus for the info hub.",
    afterText: "Connect the Industrial Edge Device (IED) to Industrial Edge Management (IEM) and configure the Databus topic for Industrial Information Hub (IIH).",
    why: "Ensures legal and editorial consistency across all Siemens Industrial Operations X customer documentation."
  },
  {
    id: "active-voice",
    ruleTitle: "Prefer Direct Active Voice Over Passive Construction",
    category: "Voice & Tone",
    explanation: "Passive voice creates ambiguity regarding who or what system component performs the action.",
    beforeText: "The JWT token should be generated by the developer before calling the IIH Semantics REST API.",
    afterText: "Generate a JWT token in the IEM Console before invoking the IIH Semantics REST API.",
    why: "Direct imperative voice gives clear, unambiguous action steps to field engineers and developers."
  },
  {
    id: "code-snippets",
    ruleTitle: "Complete & Runnable PLC / Edge App Code Snippets",
    category: "Code Snippets",
    explanation: "Avoid incomplete code blocks missing authorization headers, error handlers, or topic namespaces.",
    beforeText: "// fetch telemetry\nfetch('/api/v2/iih/variables').then(res => res.json());",
    afterText: "try {\n  const response = await fetch('/api/v2/iih/semantics/variables?asset_id=milling_01', {\n    headers: { 'Authorization': `Bearer \${iemToken}`, 'Accept': 'application/json' }\n  });\n  if (!response.ok) throw new Error(`IED API Error: \${response.status}`);\n  const data = await response.json();\n} catch (err) {\n  console.error('Failed to fetch IIH variables:', err);\n}",
    why: "Developers can copy-paste production-ready code blocks directly into their Edge Apps without syntax errors."
  },
  {
    id: "error-messages",
    ruleTitle: "Actionable Edge App Error Message Documentation",
    category: "UX & Errors",
    explanation: "Error documentations must include the exact cause, HTTP/MQTT status code, and immediate resolution steps.",
    beforeText: "Error 500: Databus broker connection lost.",
    afterText: "HTTP 422 Unprocessable Entity: `DATABUS_AUTHENTICATION_FAILED`\nCause: The X.509 client certificate supplied by Cloud Connector has expired.\nResolution: Renew device certificates in Common Configurator -> Security & Certificates.",
    why: "Empowers plant technicians and SREs to resolve Edge App deployment issues without submitting support tickets."
  }
];

export function StyleGuideSection() {
  const [activeCategory, setActiveCategory] = useState<string>("All");
  const [expandedToggles, setExpandedToggles] = useState<Record<string, boolean>>({});

  const categories = ["All", "Voice & Tone", "Terminology", "Code Snippets", "UX & Errors"];

  const filteredRules = activeCategory === "All"
    ? STYLE_RULES
    : STYLE_RULES.filter(r => r.category === activeCategory);

  const toggleRule = (id: string) => {
    setExpandedToggles(prev => ({ ...prev, [id]: !prev[id] }));
  };

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h3 className="text-xl font-bold text-foreground flex items-center gap-2">
            <BookOpen className="h-5 w-5 text-brand" />
            Technical Style Guide & Editorial Rules
          </h3>
          <p className="text-sm text-muted-foreground">
            Interactive examples of editorial guidelines and documentation standards enforced across Siemens Industrial Edge docs.
          </p>
        </div>

        {/* Category Pills */}
        <div className="flex flex-wrap gap-1.5 bg-muted/40 p-1 rounded-lg border border-border">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-3 py-1 text-xs font-medium rounded-md transition-colors ${
                activeCategory === cat
                  ? "bg-brand text-white shadow-sm font-semibold"
                  : "text-muted-foreground hover:text-foreground hover:bg-muted/60"
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      <div className="grid md:grid-cols-2 gap-4">
        {filteredRules.map((rule) => {
          const isCompliantShown = expandedToggles[rule.id] ?? true;

          return (
            <div
              key={rule.id}
              className="flex flex-col justify-between p-5 border border-border bg-surface rounded-xl hover:border-brand/40 transition-colors shadow-sm gap-4"
            >
              <div className="flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-mono font-medium px-2 py-0.5 rounded bg-brand/10 text-brand">
                    {rule.category}
                  </span>
                  <button
                    onClick={() => toggleRule(rule.id)}
                    className="text-xs font-mono font-medium text-brand hover:underline flex items-center gap-1"
                  >
                    View {isCompliantShown ? "Non-Standard" : "Style Compliant"}
                  </button>
                </div>
                <h4 className="font-semibold text-base text-foreground">{rule.ruleTitle}</h4>
                <p className="text-xs text-muted-foreground leading-relaxed">{rule.explanation}</p>
              </div>

              {/* Before / After Preview Box */}
              <div className="flex flex-col gap-2">
                {isCompliantShown ? (
                  <div className="p-3.5 bg-emerald-500/5 border border-emerald-500/20 rounded-lg flex flex-col gap-2">
                    <div className="flex items-center gap-2 text-xs font-semibold text-emerald-400 font-mono">
                      <CheckCircle2 className="h-4 w-4 text-emerald-400 shrink-0" />
                      <span>Standardized / Style Guide Compliant</span>
                    </div>
                    <pre className="text-xs font-mono text-foreground whitespace-pre-wrap leading-relaxed">
                      {rule.afterText}
                    </pre>
                  </div>
                ) : (
                  <div className="p-3.5 bg-rose-500/5 border border-rose-500/20 rounded-lg flex flex-col gap-2">
                    <div className="flex items-center gap-2 text-xs font-semibold text-rose-400 font-mono">
                      <XCircle className="h-4 w-4 text-rose-400 shrink-0" />
                      <span>Non-Standard / Deprecated Format</span>
                    </div>
                    <pre className="text-xs font-mono text-muted-foreground whitespace-pre-wrap leading-relaxed">
                      {rule.beforeText}
                    </pre>
                  </div>
                )}

                <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground pt-1 border-t border-border/40">
                  <ShieldAlert className="h-3.5 w-3.5 text-brand shrink-0" />
                  <span>Rationale: {rule.why}</span>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
